import type { editor } from "monaco-editor";

/** Monaco renders popups outside the editor surface, so use its public theme API. */
export const yarnEditorTheme: editor.IStandaloneThemeData = {
  base: "vs-dark",
  inherit: true,
  rules: [
    { token: "comment", foreground: "969696", fontStyle: "italic" },
    { token: "keyword.header", foreground: "8EAAC9" },
    { token: "type.identifier", fontStyle: "bold", foreground: "CBBB9D" },
    { token: "keyword", foreground: "B8A1CA" },
    { token: "function", foreground: "99BDB5" },
    { token: "variable", foreground: "B8AACA" },
    { token: "keyword.option", foreground: "96ADC8" },
    { token: "string", foreground: "AEC09D" },
    { token: "number", foreground: "C6AF96" },
    { token: "delimiter.node", foreground: "999999" },
    { token: "tag", foreground: "AAAAAA" },
  ],
  colors: {
    focusBorder: "#999999",
    "textLink.foreground": "#a8c7e5",
    "textLink.activeForeground": "#c3d9ed",
    "widget.shadow": "#00000055",
    "editor.background": "#1c1c1c",
    "editor.foreground": "#cdcdcd",
    "editorLineNumber.foreground": "#888888",
    "editorLineNumber.activeForeground": "#cccccc",
    "editor.lineHighlightBackground": "#282828",
    "editor.selectionBackground": "#464646",
    "editorCursor.foreground": "#cccccc",
    "editorIndentGuide.background1": "#323232",
    "editorError.foreground": "#e2a3a3",
    "editorWarning.foreground": "#d2bd8c",
    "editorBracketHighlight.foreground1": "#bbbbbb",
    "editorBracketHighlight.foreground2": "#aaaaaa",
    "editorBracketHighlight.foreground3": "#cccccc",
    "menu.background": "#282828",
    "menu.foreground": "#d0d0d0",
    "menu.border": "#3b3b3b",
    "menu.selectionBackground": "#393939",
    "menu.selectionForeground": "#f0f0f0",
    "menu.selectionBorder": "#00000000",
    "menu.separatorBackground": "#3b3b3b",
    "editorWidget.background": "#282828",
    "editorWidget.foreground": "#d0d0d0",
    "editorWidget.border": "#3b3b3b",
    "editorWidget.resizeBorder": "#999999",
    "editorHoverWidget.background": "#282828",
    "editorHoverWidget.foreground": "#d0d0d0",
    "editorHoverWidget.border": "#3b3b3b",
    "editorHoverWidget.statusBarBackground": "#2d2d2d",
    "editorSuggestWidget.background": "#282828",
    "editorSuggestWidget.foreground": "#d0d0d0",
    "editorSuggestWidget.border": "#3b3b3b",
    "editorSuggestWidget.selectedBackground": "#393939",
    "editorSuggestWidget.selectedForeground": "#f0f0f0",
    "editorSuggestWidget.highlightForeground": "#d8c79e",
    "editorSuggestWidget.focusHighlightForeground": "#eedcaa",
    "input.background": "#202020",
    "input.foreground": "#dddddd",
    "input.border": "#484848",
    "input.placeholderForeground": "#999999",
    "inputOption.activeBackground": "#444444",
    "inputOption.activeBorder": "#999999",
    "inputOption.activeForeground": "#ffffff",
    "quickInput.background": "#282828",
    "quickInput.foreground": "#d0d0d0",
    "quickInputList.focusBackground": "#393939",
    "quickInputList.focusForeground": "#f0f0f0",
  },
};
